fix: added error display to deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -95,6 +95,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SHORT_SHA: ${{ needs.outputs.outputs.short_sha }}
         run: |
+          set -e
           pnpm netlify deploy \
             --build \
             ${{ steps.var.outputs.prod_flag }} \
@@ -103,7 +104,11 @@ jobs:
             --message="${{ steps.var.outputs.deploy_message }}" \
             --telemetry-disable \
             --json \
-            > netlify.json
+            > netlify.json | {
+              echo "Netlify deployment failed. Check the logs and flags.";
+              cat netlify.json;
+              exit 1;
+          }
 
           echo "deploy_id=$(jq -r '.deploy_id' netlify.json)" >> $GITHUB_OUTPUT
           echo "deploy_url=$(jq -r '.deploy_url' netlify.json)" >> $GITHUB_OUTPUT
